---
- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: present
    update_cache: yes

- name: GlusterFS repository PPA
  apt_repository:
    repo: ppa:gluster/glusterfs-7
    state: present

- name: Update APT and install GlusterFS
  apt:
    name: glusterfs-server
    update_cache: yes

- name: Start and enable GlusterFS service
  systemd:
    name: glusterd
    state: started
    enabled: yes